Enable STUN by default
NethServer/nethserver-janus pull request #2
Opened 2017-10-30 08:16 UTC by Stell0

2017-10-30 11:30 UTC, gsanchietti requested changes
Property names should be in camel case, please change the name of following props:
- natMode -> NatMode
- publicIP -> PublicIp 
- stunPort -> StunPort
- stunServer -> StunServer

2017-10-30 11:31 UTC, gsanchietti requested changes

2017-10-30 11:31 UTC, gsanchietti commented on root/etc/e-smith/templates/opt/janus/etc/janus/janus.cfg/10base
> +        my $ip = ${'janus-gateway'}{publicIP} || die ('publicIP missing');
Try to not fail hard here.

I'd change the line 104 with something like:
```
if ($mode eq '1:1' && $publicIp ne '') {
```

2017-10-30 15:25 UTC, gsanchietti approved these changes

2017-10-30 15:27 UTC, merged

2017-10-30 16:51 UTC, Stell0 commented
nethserver-testing nethserver-janus-1.0.0-1.2.g158d2d6.ns7.noarch.rpm

2017-11-07 09:43 UTC, Stell0 commented
NethServer/dev#5373